# Generated by Django 5.0 on 2023-12-10 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_research_restaurant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
    ]
